name: Nix Flake Check Action
description: Runs `nix flake check` and generates an action summary
author: Trev
branding:
  icon: chevron-up
  color: yellow

inputs:
  args:
    description: arguments to pass to nix flake check
    required: false
    default: '-L --keep-going'

outputs:
  success:
    description: was the check successful
    value: ${{ steps.check.outputs.success }}

runs:
  using: composite
  steps:
    - name: nix flake check
      shell: bash
      id: check
      run: |
        set -o pipefail

        if nix flake check "$ARGS" 2>&1 | tee check.log ; then
            echo "success=true" >> "$GITHUB_OUTPUT"
        else
            echo "success=false" >> "$GITHUB_OUTPUT"
            logs=$(grep "nix log" check.log)
            while read n; do
                echo "### :x: $n" >> "$GITHUB_STEP_SUMMARY"
                log=$(eval "$n")
                echo "```$log```" >> "$GITHUB_STEP_SUMMARY"
            done <<< "$logs"
        fi